kafka:
    enabled: True
    producer:
        loginfo: False
        logerrors: True
        haltonerror: True
        bootstrap.servers: localhost:9092
        topic_must_exist: False
#       topic: mytopic
#       avro.schema.registry.url: url:port

