fluentd:
    export:
        enabled: False
        loginfo: True
        logerrors: True
        haltonerror: True
        app: appname
        host: localhost
        port: 8089
        nanosecond_precision: False
        topic: flan