kafka:
    enabled: True
    producer:
        loginfo: True
        logerrors: True
        haltonerror: True
        bootstrap.servers: localhost:9092
#       topic: mytopic
#       avro.schema.registry.url: url:port

      
    
  

