stomp:
    export:
        enabled: True
        loginfo: False
        logerrors: True
        haltonerror: True
        host: localhost
        port:  61613
        ssl_ca_certs: none
        ssl_cert_file: none
        ssl_cert_validator: none
        ssl_key_file: none
        ssl_version: none
        username: username
        password: password
        destination: /queue/flan
        id: 1
