splunk:
  export:
    enabled: true
    haltonerror: true
    host: localhost
    index: flan
    logerrors: true
    loginfo: false
    password: lylemays
    port: 8089
    scheme: https
    username: splunkadmin
  import:
    enabled: true
    haltonerror: true
    host: localhost
    index: flan
    logerrors: true
    loginfo: false
    password: lylemays
    port: 8089
    querycondition: none
    querytimeout: 360
    scheme: https
    time_local_splunk_field_name: timestamp
    username: splunkadmin
