settings:
  abort: False
  botfilter: seen
  delimiter: crlf
  distribution: normal
  emit : text
  end_dt: 
  excludeuatag: False
  files: 10
  gzipindex: 0
  inputformat: $remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\"
  inputsource: files
  ipfilter: 
  ipmapping: onetomany
  outputdir: /var/bret/out
  outputformat: $remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\"
  pace: False
  period: 0
  preserve_sessions: False
  quote: False
  records: 100000
  regex : 
  replay: False
  start_dt: 
  streaming: False
  streamtarget: none
  templatelogfiles: /var/bret/test1.access.log
  timeformat: %-d/%b/%Y:%H:%M:%S
  timezone: -0400
  uafilter: all
